# ChEMBL data extraction and curation

In [15]:
#import libraries
from chembl_webresource_client.new_client import new_client
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
import os   # used to check whether files exist

In [23]:
# Choose your target and endpoints here
CHEMBL_TARGET = "CHEMBL2276"
ENDPOINTS = ["Ki"]   # e.g., ["EC50"] if you prefer
RELATIONS = ["="]
THR_CLASS = 100
CONVERT_TO_LOG = False     # True for pKi/pKd style
RM_HIGH_STD = True

# File paths (edit to your VS Code workspace folders)
RAW_ALL_CSV = f"{CHEMBL_TARGET}_raw.csv"
RAW_STRUCT_FILTERED_CSV = f"{CHEMBL_TARGET}_filtered.csv"
DATA_CURATED_CSV = f"{CHEMBL_TARGET}_curated.csv"
DATA_FINAL_CSV = f"{CHEMBL_TARGET}_final.csv"

In [24]:
# Part1: Data Retrieval from ChEMBL (Optimized)

def retrieve_data(target_id=CHEMBL_TARGET,   # REVISION: was 'CHEMBL214'
                  endpoints=["Ki"], relations=["="]):
    
    activity = new_client.activity
    
    # Filter directly at the API level for faster retrieval
    res = activity.filter(
        target_chembl_id=target_id,
        standard_type__in=endpoints,
        relation__in=relations
        ).only([
        'canonical_smiles',
        'standard_type',
        'standard_value',
        'standard_units',
        'molecule_chembl_id',
        'document_chembl_id',
        'data_validity_comment',
        'activity_comment'
    ])
    
    print(f"Fetching data from ChEMBL for target {target_id}...")
    
    # Convert directly to list (single API call with filters applied server-side)
    res_list = list(res)
    print(f"Total filtered activities found: {len(res_list)}")
    
    # Use list comprehension for faster DataFrame creation
    data_list = [
        {
            'smiles': entry.get("canonical_smiles"),
            'standard_type': entry.get('standard_type'),
            'value': entry.get("standard_value"),
            'units': entry.get("standard_units"),
            'chembl_id': entry.get("molecule_chembl_id"),
            'document_chembl_id': entry.get("document_chembl_id"),
            'data_validity_comment': entry.get("data_validity_comment"),
            'activity_comment': entry.get("activity_comment"),
            'warning_flag': entry.get("data_validity_comment") is not None
        }
        for entry in res_list
    ]
    
    df = pd.DataFrame(data_list)
    print(f"\n✓ {len(df)} molecules collected with {endpoints} endpoints.")
    
    return df

# REVISION (comment 7): re-use the raw file that was already downloaded. The ChEMBL client always uses the
# CURRENT ChEMBL release, so downloading again would change the dataset. Delete <target>_raw.csv only if
# you deliberately want a new download (then report the new ChEMBL release and date in the paper).
if os.path.exists(RAW_ALL_CSV):
    df_raw = pd.read_csv(RAW_ALL_CSV)
    print(f"Using existing raw file {RAW_ALL_CSV}: {len(df_raw)} records")
else:
    df_raw = retrieve_data(CHEMBL_TARGET)   # REVISION: was retrieve_data(), which ignored CHEMBL_TARGET

Using existing raw file CHEMBL2276_raw.csv: 316 records

In [25]:
# Show columns and a preview
print("\nraw_df.columns:", list(df_raw.columns))
display(df_raw.head(10))
# Save (REVISION: only a new download is written; an existing raw file is never overwritten)
if not os.path.exists(RAW_ALL_CSV):
    df_raw.to_csv(RAW_ALL_CSV, index=False)
    print("\nSaved raw to:", RAW_ALL_CSV)

raw_df.columns: ['smiles', 'standard_type', 'value', 'units', 'chembl_id', 'document_chembl_id', 'data_validity_comment', 'activity_comment', 'warning_flag']

,smiles,standard_type,value,units,chembl_id,document_chembl_id,data_validity_comment,activity_comment,warning_flag
0,CCOc1nc(NC(C)=O)cc(N)c1C#N,Ki,190.0,nM,CHEMBL208637,CHEMBL1148638,NaN,NaN,False
1,CCOc1nc(NC(=O)Cc2cc(OC)ccc2OC)cc(N)c1C#N,Ki,2.0,nM,CHEMBL210618,CHEMBL1148638,NaN,NaN,False
2,CCOc1nc(NC(=O)Cc2cc(OC)c(S(C)(=O)=O)cc2OC)cc(N...,Ki,3.0,nM,CHEMBL210963,CHEMBL1148638,NaN,NaN,False
3,CC(=O)Nc1cc(N)c(C#N)c(-c2ccccc2)n1,Ki,550.0,nM,CHEMBL210032,CHEMBL1148638,NaN,NaN,False
4,COc1cc(S(C)(=O)=O)c(OC)cc1CC(=O)Nc1cc(N)c(C#N)...,Ki,1.0,nM,CHEMBL378627,CHEMBL1148638,NaN,NaN,False
5,CCOc1nc(NC(=O)Cc2cc(OC)c(S(C)(=O)=O)cc2OC)cc(N...,Ki,3.0,nM,CHEMBL210928,CHEMBL1148638,NaN,NaN,False
6,CCOc1nc(C(=O)NCc2ccc(S(C)(=O)=O)cc2)cc(N)c1Cl,Ki,3.8,nM,CHEMBL377383,CHEMBL1138045,NaN,NaN,False
7,CCOc1nc(C(=O)NC)cc(N)c1C#N,Ki,400.0,nM,CHEMBL211605,CHEMBL1138045,NaN,NaN,False
8,CCOc1nc(NC(=O)Cc2cc(OC)ccc2OC)cc(N)c1C#N,Ki,2.0,nM,CHEMBL210618,CHEMBL1145498,NaN,NaN,False
9,Cc1ccnc(S)n1,Ki,2060.0,nM,CHEMBL455772,CHEMBL1154397,NaN,NaN,False

In [26]:
#Part 2: Structure preparation (sanitize/neutralize), call data in, show detections, save
def _InitialiseNeutralisationReactions():
    patts = (
        # Imidazoles
        ('[n+;H]', 'n'),
        # Amines
        ('[N+;!H0]', 'N'),
        # Carboxylic acids and alcohols
        ('[$([O-]);!$([O-][#7])]', 'O'),
        # Thiols
        ('[S-;X1]', 'S'),
        # Sulfonamides
        ('[$([N-;X2]S(=O)=O)]', 'N'),
        # Enamines
        ('[$([N-;X2][C,N]=C)]', 'N'),
        # Tetrazoles
        ('[n-]', '[nH]'),
        # Sulfoxides
        ('[$([S-]=O)]', 'S'),
        # Amides
        ('[$([N-]C=O)]', 'N'),
    )
    return [(Chem.MolFromSmarts(x), Chem.MolFromSmiles(y, False)) for x, y in patts]

def sanitize_mol(smiles: str):
    if smiles is None or not isinstance(smiles, str):
        return smiles, True
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return smiles, True
    try:
        Chem.SanitizeMol(mol)
    except Exception:
        return smiles, True
    return smiles, False

def neutralize_mol(smiles: str):
    neutralized = False
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return smiles, False
    for reactant, product in _InitialiseNeutralisationReactions():
        while mol.HasSubstructMatch(reactant):
            neutralized = True
            rms = AllChem.ReplaceSubstructs(mol, reactant, product)
            mol = rms[0]
    smiles_out = Chem.MolToSmiles(mol, canonical=True, isomericSmiles=True)
    return smiles_out, neutralized

def prepare_structures(smiles: str, remove_salts=True, do_sanitize=True, do_neutralize=True):
    salt = False
    failed = False
    neutralized = False

    if smiles is None or not isinstance(smiles, str) or not smiles.strip():
        return 'missing', False, True, False

    if remove_salts:
        salt = ("." in smiles)

    if do_sanitize:
        smiles, failed = sanitize_mol(smiles)

    if do_neutralize and not failed:
        smiles, neutralized = neutralize_mol(smiles)

    return smiles, salt, failed, neutralized

# Load raw data from previous cell’s save
df_raw = pd.read_csv(RAW_ALL_CSV)

# REVISION (comment 3): keep only Ki values reported in nM (removes %, mg/ml, min-1, ug nM-1 records)
n_before = len(df_raw)
print("Units found:", df_raw['units'].value_counts(dropna=False).to_dict())
df_raw = df_raw.loc[df_raw['units'] == 'nM'].copy()
print(" - Removed non-nM records:", n_before - len(df_raw))

# Apply structure prep
prep = df_raw['smiles'].apply(lambda s: prepare_structures(s, True, True, True))
df_raw[['CuratedSmiles', 'IsSalt', 'FailedSanit', 'Neutralized']] = pd.DataFrame(prep.tolist(), index=df_raw.index)

# Analysis: what was detected at this step
print("Structure prep analysis:")
total = len(df_raw)
print(" - Input rows:", total)
print(" - IsSalt True:", int(df_raw['IsSalt'].sum()))
print(" - FailedSanit True:", int(df_raw['FailedSanit'].sum()))
print(" - Neutralized True:", int(df_raw['Neutralized'].sum()))
print(" - warning_flag True:", int(df_raw['warning_flag'].sum()))
print(" - Unique CuratedSmiles:", df_raw['CuratedSmiles'].nunique())

# Now filter (remove salts, failed, and warning_flag)
f1 = df_raw.loc[~df_raw['IsSalt']].copy()
f2 = f1.loc[~f1['FailedSanit']].copy()
struct_df = f2.loc[~f2['warning_flag']].copy()

# Duplicates overview AFTER filtering
dup_counts = struct_df['CuratedSmiles'].value_counts()
dup_groups = (dup_counts > 1).sum()
dup_extra_rows = int(dup_counts[dup_counts > 1].sum() - dup_groups)

print("\nPost-filter analysis:")
print(" - Remaining rows:", len(struct_df))
print(" - Removed salts:", total - len(f1))
print(" - Removed failed sanitization:", len(f1) - len(f2))
print(" - Removed warning_flag:", len(f2) - len(struct_df))
print(" - Duplicate groups:", int(dup_groups))
print(" - Extra duplicate rows:", int(dup_extra_rows))

print("\nstruct_df.columns:", list(struct_df.columns))
display(struct_df.head(10))

# Save
# struct_df.to_csv(RAW_STRUCT_FILTERED_CSV, index=False)
print("\nSaved structure-filtered to:", RAW_STRUCT_FILTERED_CSV)
struct_df.to_csv(RAW_STRUCT_FILTERED_CSV, index=False)

Units found: {'nM': 316}
 - Removed non-nM records: 0
Structure prep analysis:
 - Input rows: 316
 - IsSalt True: 0
 - FailedSanit True: 0
 - Neutralized True: 1
 - warning_flag True: 0
 - Unique CuratedSmiles: 299

Post-filter analysis:
 - Remaining rows: 316
 - Removed salts: 0
 - Removed failed sanitization: 0
 - Removed warning_flag: 0
 - Duplicate groups: 16
 - Extra duplicate rows: 17

struct_df.columns: ['smiles', 'standard_type', 'value', 'units', 'chembl_id', 'document_chembl_id', 'data_validity_comment', 'activity_comment', 'warning_flag', 'CuratedSmiles', 'IsSalt', 'FailedSanit', 'Neutralized']

,smiles,standard_type,value,units,chembl_id,document_chembl_id,data_validity_comment,activity_comment,warning_flag,CuratedSmiles,IsSalt,FailedSanit,Neutralized
0,CCOc1nc(NC(C)=O)cc(N)c1C#N,Ki,190.0,nM,CHEMBL208637,CHEMBL1148638,NaN,NaN,False,CCOc1nc(NC(C)=O)cc(N)c1C#N,False,False,False
1,CCOc1nc(NC(=O)Cc2cc(OC)ccc2OC)cc(N)c1C#N,Ki,2.0,nM,CHEMBL210618,CHEMBL1148638,NaN,NaN,False,CCOc1nc(NC(=O)Cc2cc(OC)ccc2OC)cc(N)c1C#N,False,False,False
2,CCOc1nc(NC(=O)Cc2cc(OC)c(S(C)(=O)=O)cc2OC)cc(N...,Ki,3.0,nM,CHEMBL210963,CHEMBL1148638,NaN,NaN,False,CCOc1nc(NC(=O)Cc2cc(OC)c(S(C)(=O)=O)cc2OC)cc(N...,False,False,False
3,CC(=O)Nc1cc(N)c(C#N)c(-c2ccccc2)n1,Ki,550.0,nM,CHEMBL210032,CHEMBL1148638,NaN,NaN,False,CC(=O)Nc1cc(N)c(C#N)c(-c2ccccc2)n1,False,False,False
4,COc1cc(S(C)(=O)=O)c(OC)cc1CC(=O)Nc1cc(N)c(C#N)...,Ki,1.0,nM,CHEMBL378627,CHEMBL1148638,NaN,NaN,False,COc1cc(S(C)(=O)=O)c(OC)cc1CC(=O)Nc1cc(N)c(C#N)...,False,False,False
5,CCOc1nc(NC(=O)Cc2cc(OC)c(S(C)(=O)=O)cc2OC)cc(N...,Ki,3.0,nM,CHEMBL210928,CHEMBL1148638,NaN,NaN,False,CCOc1nc(NC(=O)Cc2cc(OC)c(S(C)(=O)=O)cc2OC)cc(N...,False,False,False
6,CCOc1nc(C(=O)NCc2ccc(S(C)(=O)=O)cc2)cc(N)c1Cl,Ki,3.8,nM,CHEMBL377383,CHEMBL1138045,NaN,NaN,False,CCOc1nc(C(=O)NCc2ccc(S(C)(=O)=O)cc2)cc(N)c1Cl,False,False,False
7,CCOc1nc(C(=O)NC)cc(N)c1C#N,Ki,400.0,nM,CHEMBL211605,CHEMBL1138045,NaN,NaN,False,CCOc1nc(C(=O)NC)cc(N)c1C#N,False,False,False
8,CCOc1nc(NC(=O)Cc2cc(OC)ccc2OC)cc(N)c1C#N,Ki,2.0,nM,CHEMBL210618,CHEMBL1145498,NaN,NaN,False,CCOc1nc(NC(=O)Cc2cc(OC)ccc2OC)cc(N)c1C#N,False,False,False
9,Cc1ccnc(S)n1,Ki,2060.0,nM,CHEMBL455772,CHEMBL1154397,NaN,NaN,False,Cc1ccnc(S)n1,False,False,False

Saved structure-filtered to: CHEMBL2276_filtered.csv

In [27]:
#Part 4: Experimental curation (Dixon’s Q, stats), call data inside, show detections, save
# JUPYTER CELL 4: Load struct → outlier filtering + stats → analysis → save

def _InitLookUp(alpha=0.05):
    if alpha == 0.10:
        q_tab = [0.941, 0.765, 0.642, 0.56, 0.507, 0.468, 0.437, 0.412, 0.392, 0.376, 0.361, 0.349, 0.338, 0.329,
                 0.32, 0.313, 0.306, 0.3, 0.295, 0.29, 0.285, 0.281, 0.277, 0.273, 0.269, 0.266, 0.263, 0.26]
    elif alpha == 0.05:
        q_tab = [0.97, 0.829, 0.71, 0.625, 0.568, 0.526, 0.493, 0.466, 0.444, 0.426, 0.41, 0.396, 0.384, 0.374,
                 0.365, 0.356, 0.349, 0.342, 0.337, 0.331, 0.326, 0.321, 0.317, 0.312, 0.308, 0.305, 0.301, 0.29]
    elif alpha == 0.01:
        q_tab = [0.994, 0.926, 0.821, 0.74, 0.68, 0.634, 0.598, 0.568, 0.542, 0.522, 0.503, 0.488, 0.475, 0.463,
                 0.452, 0.442, 0.433, 0.425, 0.418, 0.411, 0.404, 0.399, 0.393, 0.388, 0.384, 0.38, 0.376, 0.372]
    else:
        q_tab = []
    return {n: q for n, q in zip(range(3, len(q_tab)+1), q_tab)}

def dixon_test(data, left=True, right=True, alpha=0.05):
    q_dict = _InitLookUp(alpha=alpha)
    if not (3 <= len(data) <= max(q_dict.keys(), default=0)):
        return []
    sdata = sorted(data)
    Q_mindiff, Q_maxdiff = (0, 0), (0, 0)
    if left:
        Q_min = (sdata[1] - sdata[0])
        try:
            Q_min /= (sdata[-1] - sdata[0])
            Q_mindiff = (Q_min - q_dict[len(data)], sdata[0])
        except ZeroDivisionError:
            pass
    if right:
        Q_max = abs((sdata[-2] - sdata[-1]))
        try:
            Q_max /= abs((sdata[0] - sdata[-1]))
            Q_maxdiff = (Q_max - q_dict[len(data)], sdata[-1])
        except ZeroDivisionError:
            pass

    if not Q_mindiff[0] > 0 and not Q_maxdiff[0] > 0:
        return []
    if Q_mindiff[0] == Q_maxdiff[0]:
        return [Q_mindiff[1], Q_maxdiff[1]]
    if Q_mindiff[0] > Q_maxdiff[0]:
        return [Q_mindiff[1]]
    return [Q_maxdiff[1]]

def compute_stats(values: np.ndarray):
    n = len(values)
    mean = float(np.mean(values)) if n else np.nan
    std = float(np.std(values, ddof=0)) if n else np.nan
    sem = float(std/np.sqrt(n)) if n else np.nan
    return mean, std, sem, n

def concatenate_string_info(data: pd.DataFrame, outlier_idx):
    st = data["standard_type"]
    ddoc = data["document_chembl_id"]
    mid = data["chembl_id"]
    if len(outlier_idx) > 0:
        st = st.drop(st.index[outlier_idx], errors='ignore')
        ddoc = ddoc.drop(ddoc.index[outlier_idx], errors='ignore')
        mid = mid.drop(mid.index[outlier_idx], errors='ignore')
    standard_types = ",".join(sorted(set(st.astype(str))))
    chembl_docs_ids = ",".join(sorted(set(ddoc.astype(str))))
    chembl_ids = ",".join(sorted(set(mid.astype(str))))
    return chembl_ids, chembl_docs_ids, standard_types

def curate_values(values: np.ndarray, outlier_test=True, alpha=0.05, convert_to_log=False):
    if convert_to_log:
        values = -np.log10(values / 1e9)  # p-scale from nM
    new_values = values.copy()
    outlier_idx = []
    num_outliers = 0
    if outlier_test:
        outs = dixon_test(list(values), True, True, alpha=alpha)
        if len(outs) > 0:
            mask = np.isin(values, np.array(outs))
            outlier_idx = list(np.where(mask)[0])
            new_values = values[~mask]
            num_outliers = int(mask.sum())
    mean, std, sem, n = compute_stats(new_values)
    return mean, std, sem, num_outliers, n, new_values, outlier_idx

# Load structure-filtered data
struct_df = pd.read_csv(RAW_STRUCT_FILTERED_CSV)

# Prepare numeric values
work = struct_df.copy()
work['value'] = pd.to_numeric(work['value'], errors='coerce')
work = work.dropna(subset=['CuratedSmiles', 'value'])

unique_smiles = work['CuratedSmiles'].unique()
rows = []
total_outliers = 0
groups_with_outliers = 0

for smi in unique_smiles:
    data = work.loc[work['CuratedSmiles'] == smi]
    vals = data['value'].values.astype(float)
    mean, std, sem, n_out, n_vals, new_vals, out_idx = curate_values(
        vals, outlier_test=True, alpha=0.05, convert_to_log=CONVERT_TO_LOG
    )
    if n_out > 0:
        groups_with_outliers += 1
        total_outliers += n_out
    chembl_ids, chembl_docs_ids, standard_types = concatenate_string_info(data, out_idx)
    rows.append({
        'smiles': smi,
        'exp_mean': mean,
        'exp_std': std,
        'exp_sem': sem,
        'no.entries': int(len(vals)),
        'no.outliers': int(n_out),
        'standard_types': standard_types,
        'chembl_id': chembl_ids,
        'chembl_id_doc': chembl_docs_ids
    })

exp_df = pd.DataFrame(rows)

# Remove high-std groups (mimic log10(std) >= 1 => std >= 10)
before_groups = len(exp_df)
if RM_HIGH_STD:
    exp_df = exp_df.loc[~(exp_df['exp_std'] >= 10)].copy()
removed_high_std = before_groups - len(exp_df)

# Analysis
print("Experimental curation analysis:")
print(" - Input groups (unique CuratedSmiles):", len(unique_smiles))
print(" - Groups with outliers:", groups_with_outliers)
print(" - Total outliers removed:", total_outliers)
print(" - Removed high-std groups (std >= 10):", removed_high_std)
print(" - Final groups:", len(exp_df))

print("\nexp_df.columns:", list(exp_df.columns))
display(exp_df.head(10))

# Save
exp_df.to_csv(DATA_CURATED_CSV, index=False)
print("\nSaved curated to:", DATA_CURATED_CSV)

Experimental curation analysis:
 - Input groups (unique CuratedSmiles): 299
 - Groups with outliers: 1
 - Total outliers removed: 1
 - Removed high-std groups (std >= 10): 1
 - Final groups: 298

exp_df.columns: ['smiles', 'exp_mean', 'exp_std', 'exp_sem', 'no.entries', 'no.outliers', 'standard_types', 'chembl_id', 'chembl_id_doc']

,smiles,exp_mean,exp_std,exp_sem,no.entries,no.outliers,standard_types,chembl_id,chembl_id_doc
0,CCOc1nc(NC(C)=O)cc(N)c1C#N,194.7650,4.7650,3.369364,2,0,Ki,CHEMBL208637,"CHEMBL1148638,CHEMBL1201862"
1,CCOc1nc(NC(=O)Cc2cc(OC)ccc2OC)cc(N)c1C#N,2.0000,0.0000,0.000000,3,1,Ki,CHEMBL210618,"CHEMBL1145498,CHEMBL1148638"
2,CCOc1nc(NC(=O)Cc2cc(OC)c(S(C)(=O)=O)cc2OC)cc(N...,3.0810,0.0810,0.057276,2,0,Ki,CHEMBL210963,"CHEMBL1148638,CHEMBL1201862"
4,COc1cc(S(C)(=O)=O)c(OC)cc1CC(=O)Nc1cc(N)c(C#N)...,2.0810,1.0810,0.764382,2,0,Ki,CHEMBL378627,"CHEMBL1148638,CHEMBL1201862"
5,CCOc1nc(NC(=O)Cc2cc(OC)c(S(C)(=O)=O)cc2OC)cc(N...,3.4905,0.4905,0.346836,2,0,Ki,CHEMBL210928,"CHEMBL1148638,CHEMBL1201862"
6,CCOc1nc(C(=O)NCc2ccc(S(C)(=O)=O)cc2)cc(N)c1Cl,3.8905,0.0905,0.063993,2,0,Ki,CHEMBL377383,"CHEMBL1138045,CHEMBL1201862"
7,CCOc1nc(C(=O)NC)cc(N)c1C#N,400.0000,0.0000,0.000000,1,0,Ki,CHEMBL211605,CHEMBL1138045
8,Cc1ccnc(S)n1,2060.0000,0.0000,0.000000,1,0,Ki,CHEMBL455772,CHEMBL1154397
9,CC(C)Nc1nccc(-c2c[nH]nc2-c2ccc(Cl)cc2)n1,48.0000,0.0000,0.000000,1,0,Ki,CHEMBL451282,CHEMBL1154397
10,Clc1ccc(-c2n[nH]cc2-c2ccnc(NC3CC3)n2)cc1,151.0000,0.0000,0.000000,1,0,Ki,CHEMBL521016,CHEMBL1154397

Saved curated to: CHEMBL2276_curated.csv

In [28]:
#Part 5 Class assignment, call curated data inside, show results, save

def class_vector(table_final: pd.DataFrame, thr_class: float):
    out = pd.DataFrame({
        'smiles': table_final['smiles'],
        'chembl_id': table_final['chembl_id'],
        'exp_mean [nM]': table_final['exp_mean'],
    })
    out['class'] = table_final['exp_mean'] < thr_class
    return out

# Load curated
exp_df = pd.read_csv(DATA_CURATED_CSV)

final_df = class_vector(exp_df, THR_CLASS)

# Analysis
n = len(final_df)
n_active = int(final_df['class'].sum())
print("Class assignment analysis:")
print(" - Total compounds:", n)
print(" - Active (exp_mean < {} nM):".format(THR_CLASS), n_active)
print(" - Inactive:", n - n_active)
print(" - % Active:", round(100.0 * n_active / n, 2) if n > 0 else 0)

print("\nfinal_df.columns:", list(final_df.columns))
display(final_df.head(10))

# Save
final_df.to_csv(DATA_FINAL_CSV, index=False)
print("\nSaved final to:", DATA_FINAL_CSV)

Class assignment analysis:
 - Total compounds: 298
 - Active (exp_mean < 100 nM): 50
 - Inactive: 248
 - % Active: 16.78

final_df.columns: ['smiles', 'chembl_id', 'exp_mean [nM]', 'class']

,smiles,chembl_id,exp_mean [nM],class
0,CCOc1nc(NC(C)=O)cc(N)c1C#N,CHEMBL208637,194.7650,False
1,CCOc1nc(NC(=O)Cc2cc(OC)ccc2OC)cc(N)c1C#N,CHEMBL210618,2.0000,True
2,CCOc1nc(NC(=O)Cc2cc(OC)c(S(C)(=O)=O)cc2OC)cc(N...,CHEMBL210963,3.0810,True
3,COc1cc(S(C)(=O)=O)c(OC)cc1CC(=O)Nc1cc(N)c(C#N)...,CHEMBL378627,2.0810,True
4,CCOc1nc(NC(=O)Cc2cc(OC)c(S(C)(=O)=O)cc2OC)cc(N...,CHEMBL210928,3.4905,True
5,CCOc1nc(C(=O)NCc2ccc(S(C)(=O)=O)cc2)cc(N)c1Cl,CHEMBL377383,3.8905,True
6,CCOc1nc(C(=O)NC)cc(N)c1C#N,CHEMBL211605,400.0000,False
7,Cc1ccnc(S)n1,CHEMBL455772,2060.0000,False
8,CC(C)Nc1nccc(-c2c[nH]nc2-c2ccc(Cl)cc2)n1,CHEMBL451282,48.0000,True
9,Clc1ccc(-c2n[nH]cc2-c2ccnc(NC3CC3)n2)cc1,CHEMBL521016,151.0000,False

Saved final to: CHEMBL2276_final.csv